### Raiz da aplicação
GET http://localhost:5008/

### Listagem de Produtos
GET http://localhost:5008/produto/listar

### Busca de Produtos por nome
GET http://localhost:5008/produto/buscar/Televisão

### Cadastro de Produtos
POST http://localhost:5008/produto/cadastrar