### Raiz da aplicação
GET http://localhost:5008/

### Listagem de Produtos
GET http://localhost:5008/produto/listar

### Busca de Produtos por nome
GET http://localhost:5008/produto/buscar/Televisão

### Cadastro de Produtos
POST http://localhost:5008/produto/cadastrar
Content-Type: application/json

{
    "nome" : "camelo",
    "descricao" : "pequeno",
    "valor" : 204
}

### Remoção de um produto
DELETE http://localhost:5008/produto/deletar/Feijão

### Alteração de um produto
PATCH  http://localhost:5008/produto/alterar/Feijão/Alimento alterado